### ISSUE TITLE
Source File for architecture diagram?

### ISSUE THREAD

**Issue by aravind-murthy** [aws-quickstart/quickstart-amazon-redshift#32]
Would it be possible to make the source file (PPT?) used for the architecture diagram seen in https://github.com/aws-quickstart/quickstart-amazon-redshift/blob/develop/README.md so that we can use that diagram as a starting point for our own designs?

Perhaps by creating a new folder at the base/root of the repo called diagrams and then uploading the powerpoint there?

Thank you.

**Comment by sudhig** [comment]
We don't store PPT in the git repo. Please share you email and I will share with you.

**Comment by aravind-murthy** [comment]
Hi @sudhig how do i share my email with you, without typing it here? Thanks.

**Comment by sudhig** [comment]
Aravind - Just provide your email address here and I will forward it to you.
